# =====================================================================
# SIT Profile - System Integration Testing (developerxgroup.ddns.net)
# =====================================================================
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/diwan_logging?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=Dev_user
spring.datasource.password=Dev@1234

spring.kafka.bootstrap-servers=host.docker.internal:9092
